service/src/components/LotteryLounge/LotteryCanvas.tsx
service/src/components/LotteryLounge/Modal/LoseModal.tsx
service/tailwind.config.js

미당첨 모달 구현
미당첨 모달 구현
클립보드 복사 기능 구현
fade out 후 미당첨 모달 팝업
클립보드 복사 기능도 추가했어여

[Feat] 미당첨 모달 구현

---

service/src/components/MainPage/RendingSection.tsx
service/src/components/common/Comment/Comment.tsx
service/src/index.css
service/src/pages/CommentsLoungePage.tsx
service/src/router.tsx
service/src/store/context/useLoginContext.tsx
service/tailwind.config.js

기대평 페이지 구현
기대평 comment css 수정
기대평 UI 구현
close #28
실시간 띄우기 애니메이션 + 소켓 공부 필요~

기대평 페이지 구현

---

admin/src/components/common/Modal.tsx
admin/tailwind.config.js

공통 모달 컴포넌트 구현
```
/**
* Modal Component
* @param Element
* @param isButton : 버튼 사용 여부
* @param handleCloseClick : 모달 close 핸들러 함수
* @param handleButtonClick : 모달 버튼 핸들러 함수
* @returns
*/
```
JsDoc에 필요한 파라미터 적어 놨습니다.
close #47

[Feat] 모달 컴포넌트 구현

---

admin/.yarnrc.yml
admin/package.json
admin/src/components/ui/Barchart.tsx
admin/src/components/ui/calendar.tsx
admin/src/components/ui/chart.tsx
admin/src/components/ui/datetime-picker.tsx
admin/src/pages/EventMetricsPage.tsx
admin/tsconfig.json
admin/vite.config.ts

어드민 지표 페이지 바 차트 구현
어드민 지표 페이지 바 차트 구현
close #41

[Feat] 어드민 지표 페이지 바 차트 구현

---

admin/yarn.lock

hotfix : yarn.lock 수정

---

service/package.json
service/src/constants/lib/constants.ts
service/yarn.lock

react query 간단한 세팅
- react query 설치
- baseURL, header 상수 추가
close #61 
yarn install 필수

[Feat] react query 간단한 세팅

---

admin/src/components/common/List/WinnerList.tsx
admin/src/components/ui/Barchart.tsx
admin/src/pages/EventManagementPage.tsx
admin/src/pages/EventMetricsPage.tsx
admin/src/pages/WinManagementPage.tsx
service/src/components/MainPage/CarInfoSection/VideoPlayer.tsx
service/src/components/MainPage/EventSection/EventSection.tsx
service/src/components/MainPage/EventSection/LoginModal/LoginModal.tsx
service/src/components/common/Badge/Badge.tsx
service/src/components/common/Footer/EventInfoFooter.tsx
service/src/components/common/Footer/Footer.tsx
service/src/hooks/MainPage/useScrollControl.ts
service/src/pages/LotteryLounge.tsx
service/src/pages/MainPage.tsx
service/src/pages/QuizLoungePage.tsx

피드백을 바탕으로 전체적으로 수정
Service
Admin
close #64

[Fix] 피드백 반영 후 수정

---

admin/src/apis/main/api.ts
admin/src/apis/main/query.ts
admin/src/components/EventManagement/FCFSModal.tsx
admin/src/components/EventManagement/RaffleModal.tsx
admin/src/components/common/Container/SetFCFSWinnerContainer.tsx
admin/src/components/common/Container/SetRaffleWinnerContainer.tsx
admin/src/components/common/List/WinnerList.tsx
admin/src/components/common/List/list.tsx
admin/src/components/section/EventManagement.tsx
admin/src/constants/api.ts
admin/src/utils/getWeekDay.ts
service/.yarn/.vite/deps/_metadata.json
service/src/apis/authorization.ts
service/src/apis/main/api.ts
service/src/components/MainPage/EventSection/EventSection.tsx
service/src/constants/lib/constants.ts

어드민 메인 페이지 api 연동
어드민 메인 페이지 
이벤트 관리 api 연동
당첨 관리 api 연동
error boundary 문제가 뜰 경우, fetch 자체가 비활성화 된다.
close #80

[Feat] 어드민 메인 페이지 api 연동

---

admin/src/apis/winManagement/api.ts

[Fix]: header 수정

---

service/src/components/common/Header/Header.tsx
service/src/pages/CommentsLoungePage.tsx

헤더 사라지는 오류 수정
헤더 사라지는 오류 수정
close #87

[Fix] 헤더 사라지는 오류 수정

---

service/package.json
service/src/components/LotteryLounge/LotteryCanvas.tsx
service/src/components/QuizLounge/QuizContainer.tsx
service/src/hooks/QuizLounge/useInitialArrays.tsx
service/src/pages/QuizLoungePage.tsx
service/src/utils/confettiCrafter.ts
service/yarn.lock

confetti 라이브러리 추가 및 구현
- confetti 라이브러리 추가 및 구현
close #86 
yarn install 필요합니당
https://github.com/user-attachments/assets/888bd4a1-f685-4123-ab27-9689441c6166
https://github.com/user-attachments/assets/ad8917f6-257b-4db2-abc6-b6ae57f90c24

[Feat] confetti 라이브러리 추가 및 구현

---

admin/src/components/EventManagement/FCFSModal.tsx
admin/src/components/EventManagement/RaffleModal.tsx
admin/src/hooks/useFcFsRequest.tsx
admin/src/hooks/useRaffleRequest.tsx

modal state, effect 훅으로 분리
refactor : state, effect 훅으로 분리
close #95

[Refactor] 이벤트 모달 커스텀 훅 분리

---

service/src/apis/shareurl/api.ts
service/src/apis/shareurl/query.ts
service/src/components/MainPage/EventSection/LoginModal/LoginModal.tsx
service/src/components/common/Tooltip/Tooltip.tsx
service/src/main.tsx
service/src/store/context/useUrl.tsx
service/src/store/provider/UrlProvider.tsx
service/src/utils/cookie.ts

공유 url api 연동
공유 url context, provider 적용
버튼 클릭시 사이트 url or 코드 포함된 사이트 url 복사
close #92

[Feat] 공유 url api 연동

---

admin/src/apis/event/api.tsx
admin/src/apis/event/query.tsx
admin/src/apis/eventMetrics/api.tsx
admin/src/apis/eventMetrics/query.tsx
admin/src/apis/main/api.ts
admin/src/apis/main/query.ts
admin/src/apis/winManagement/api.ts
admin/src/apis/winManagement/query.ts
admin/src/components/WinManagement/InputField.tsx
admin/src/components/WinManagement/NumberOfWinnersModal.tsx
admin/src/components/WinManagement/WinnersProbabilitiesModal.tsx
service/src/apis/draw/api.ts
service/src/apis/quizLounge/api.ts
service/src/apis/quizLounge/query.ts
service/src/apis/shareurl/api.ts

cookies 값을 가져오지 못하는 오류 수정
- 쿼리 내부에서 토큰 값 가져올 수 있게 수정
- 추가로 값이 없을 때 유효성 검증 안했길래 같이 수정해버림
close #126 
근데 똑같은 코드가 반복되는게 좋은 코드인지는 잘 모르겠음 🥲

[Fix] cookies 값을 가져오지 못하는 오류 수정

---

service/src/App.tsx
service/src/components/ErrorPage/ErrorBoundaryPage.tsx
service/src/components/ErrorPage/NotFoundPage.tsx
service/src/main.tsx
service/src/router.tsx

[Feat] 에러 페이지 구현

---

service/src/components/ErrorPage/UnauthorizedPage.tsx
service/src/components/common/ProtectedRoute/ProtectedRoute.tsx
service/src/router.tsx

Protected Route 설정 
Protected Route 설정 
401 Page 구현 - 로그인 안하고 해당 페이지 들어갈 경우 
3초 뒤에 메인으로 redirect
close #114

[Feat] Protected Route 설정 

---

service/src/apis/main/api.ts
service/src/apis/main/query.ts
service/src/components/MainPage/EventSection/EventSection.tsx
service/src/components/MainPage/RendingSection.tsx
service/src/types/main/eventInfoType.ts

동적/정적 이벤트 api 분리 및 연동
- 동적 이벤트 api, 커스텀훅 분리
- 정적 이벤트 api, 커스텀훅 분리
close #133

[Refactor] 동적/정적 이벤트 api 분리 및 연동

---

service/src/apis/login/api.ts
service/src/apis/login/query.ts
service/src/constants/lib/constants.ts
service/src/pages/ShareHandler.tsx
service/src/router.tsx

공유 url code 추출
- 공유 url 경로 변수 지정
-  공유 url로 들어갈경우, localstorage에 저장 후 메인으로 Redirect
-  login 시 코드가 있을 경우, 해당 코드를 header 에 넣어서 전송
close #136

[Feat] 공유 url - code 추출

---

service/src/App.tsx
service/src/components/LotteryLounge/LotteryCanvas.tsx
service/src/components/LotteryLounge/Modal/LoseModal.tsx
service/src/components/MainPage/DrawSection/DrawSection.tsx
service/src/components/MainPage/EventIntroductionSection.tsx
service/src/components/MainPage/FcfsSection/FcfsSection.tsx
service/src/main.tsx
service/src/pages/LotteryLounge.tsx
service/src/pages/MainPage.tsx
service/src/pages/QuizLoungePage.tsx
service/src/store/context/useEventDateContext.tsx
service/src/store/provider/EventDateProvider.tsx

사소한 변경사항
- 모달 안닫히는 문제 수정/모달 중복으로 열리는 문제 해결
- 문구 수정
- static 으로 선언한 정보 -> api 로부터 받게 수정 
- lose modal - url 안보이는 문제 수정
- 푸터 날짜 사라지는 문제 해결
- eventdate context date, setdate 분리
close #142

[Fix] 사소한 변경사항

---

service/src/App.tsx
service/src/pages/MainPage.tsx

footer 스크롤 먹히는 이슈 수정
footer 스크롤 먹히는 이슈 수정
close #141

[Fix] footer 스크롤 먹히는 이슈 수정

---

service/src/components/CommentsLounge/CommentButtonContainer.tsx
service/src/components/CommentsLounge/CommentsContainer.tsx

댓글 버튼 비활성화 오류 수정
댓글 버튼 비활성화 오류 수정
close #159

[Fix] 댓글 버튼 비활성화 오류 수정

---

service/src/components/CommentsLounge/CommentsContainer.tsx

[Hotfix] 기대평 오류 수정

---

service/src/components/MainPage/EventSection/LoginModal/LoginModal.tsx

[Hotfix] 전화번호 인증 받도록 변경

---

service/package.json
service/src/components/LotteryLounge/Modal/LoseModal.tsx
service/src/components/MainPage/EventSection/LoginModal/LoginModal.tsx
service/src/components/common/Toast/Toast.tsx
service/vite.config.ts
service/yarn.lock

Url 공유 시 토스트 알람 뜨게 구현
Url 공유 시 토스트 알람 뜨게 구현
close #180

[Feat] Url 공유 시 토스트 알람 뜨게 구현

---

admin/src/pages/LoginPage.tsx

어드민 로그인 실패 시 메인으로 넘어가는 오류 수정
어드민 로그인 실패 시 메인으로 넘어가는 오류 수정
close #186

[Fix] 어드민 로그인 실패 시 메인으로 넘어가는 오류 수정

---

service/src/components/LotteryLounge/Modal/LoseModal.tsx
service/src/components/MainPage/EventSection/LoginModal/LoginModal.tsx
service/src/components/common/Input/Input.tsx
service/src/constants/error.ts

로그인 모달 유효성 검증 추가
로그인 모달 이미 등록된 유저는 alert창 띄운후, 필드 초기화
close #151

[Fix] 로그인 모달 유효성 검증 추가

---

service/src/components/MainPage/EventSection/LoginModal/LoginModal.tsx

전화번호 인증 query 변경
전화번호 인증 query 변경

[Hotfix] 전화번호 인증 query 변경

---

service/src/pages/QuizLoungePage.tsx

튜토리얼 사이트 Blocker 삭제
튜토리얼 사이트 Blocker 삭제

[Hotfix] 튜토리얼 사이트 Blocker 삭제

---

admin/src/components/EventManagement/FCFSModal.tsx
admin/src/components/EventManagement/RaffleModal.tsx
admin/src/hooks/useFcFsRequest.tsx
admin/src/hooks/useRaffleRequest.tsx
admin/src/pages/EventManagementPage.tsx

어드민 이벤트 관리 수정
- 선착순 모달창에서 기존 데이터 띄운 후 수정
- 추첨이벤트 모달에서 기존 시간 띄운 후 수정
- 툴팁으로 이벤트 조건 확인
- 유효성 검증 추가 - 시간은 alert로, 날짜는 항상 같은 주가 되도록 변경
close #184

[Fix] 어드민 이벤트 관리 수정

---

service/src/components/MainPage/CarInfoSection/Carousel.css
service/src/components/MainPage/CarInfoSection/Carousel.tsx
service/src/components/MainPage/EventSection/LoginModal/LoginModal.tsx
service/src/constants/animation.ts

로그인 시 새로고침 막음
- 로그인 성공 시 강제 새로고침막고 Url 가져오는 쿼리 새롭게 호출
close #203 
https://github.com/user-attachments/assets/15983f65-0e64-457c-9ac7-17eb76472c0d

[Fix] 로그인 시 새로고침 막음

---

service/src/components/MainPage/CarInfoSection/Carousel.css
service/src/components/MainPage/CarInfoSection/Carousel.tsx
service/src/components/MainPage/EventSection/LoginModal/LoginModal.tsx
service/src/constants/animation.ts

이미지 캐러셀 더 자연스럽게 수정
- 이미지 캐러셀 더 자연스럽게 수정
close #205
https://github.com/user-attachments/assets/52316fec-3f1d-469e-a6e9-1ae4d271fec9

[Fix] 이미지 캐러셀 더 자연스럽게 수정

---

admin/index.html

admin favicon, title 변경
admin favicon, title 변경

[Fix] admin favicon, title 변경

---

admin/index.html

[Hotfix] 어드민 오류 수정

---

service/src/constants/lib/constants.ts
service/src/pages/LotteryLounge.tsx
service/src/router.tsx

이벤트 기간 아닐때 보여주는 페이지 이동하지 않는 문제 수정
router 수정 - not-event-period 추가
blocker 수정 - eventperiod일때만 뜨도록
close #213

[Hotfix] 이벤트 기간 아닐때 보여주는 페이지 이동하지 않는 문제 수정

---

service/src/components/MainPage/CarInfoSection/Carousel.tsx
service/src/components/MainPage/CarInfoSection/VideoPlayer.tsx
service/src/hooks/MainPage/useVideoMetaData.tsx
service/src/utils/main/getTransformClass.ts
service/src/utils/main/getVisibleItems.ts

이미지 캐러셀 오류 수정
-  이미지 캐러셀 오류 수정
- 약간의 리팩토링
#216

[Fix] 이미지 캐러셀 오류 수정

---

service/src/pages/MainPage.tsx

이벤트 기간아닐시 페이지 안보이는 문제 해결
이벤트 기간아닐시 페이지 안보이는 문제 해결
close #219

[Hotfix] 이벤트 기간아닐시 페이지 안보이는 문제 해결
